// @ts-check

/**
 * The sidebar is hand-written rather than autogenerated: the reading order of these pages is
 * load-bearing (what it is → how to run one → what a run promises → the wire), and an
 * alphabetical or filesystem order would scramble it.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  docsSidebar: [
    'index',
    'quickstart',
    {
      type: 'category',
      label: 'The three promises',
      collapsed: false,
      items: ['hermetic', 'control-seam', 'frames'],
    },
    {
      type: 'category',
      label: 'Protocol',
      collapsed: false,
      items: ['protocol/events', 'protocol/commands'],
    },
    {
      type: 'category',
      label: 'Harnesses',
      items: ['harnesses/claude', 'harnesses/codex'],
    },
    {
      type: 'category',
      label: 'Reference',
      items: ['reference/cli', 'reference/library'],
    },
    'status',
  ],
};

export default sidebars;
